# allgemein
env:
  AUTH_PORT: MzAwMA==
  DB_HOST: ImxvY2FsaG9zdCI=
  DB_NAME: ImJ1ZGdldGJvb2si
  DB_PASSWORD: ImFkbWluIg==
  DB_PORT: IjMzMDYi
  DB_USER: InJvb3Qi
  EXPENSE_PORT: MzAwMA==
  GOOGLE_CALLBACK_URL: aHR0cHM6Ly9idWRnZXRib29rLm1lL2FwaS9hdXRoL2dvb2dsZS9yZWRpcmVjdAo=
  GOOGLE_CLIENT_ID: NjAzNjgxNTI4NjQyLTA1ZnE4YWZyMmZnbGJkYWJtODUzMmpqZzFxYmY5MXJhLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tCg==
  GOOGLE_CLIENT_SECRET: R09DU1BYLWFUNG9Od1FmMXRLaUlxM1NKUC1YQUV3S1hTeGEK
  JWT_SECRET: ODI5YzRkYjdlNDYxNTM2NGIwZDMxNDIyYzVhYjUzNmVjNWQzNTQyY2ViMjZhMjVmMmI2OGRhNTI3Y2ZhOGJhMgo=
  REDIRECT_HOST: aHR0cHM6Ly9idWRnZXRib29rLm1lCg==

# auth
auth:
  DEPLOYMENT_CONTAINER_PORT: MzAwMA==
  SERVICE_PORT: MzAwMA==
  SERVICE_TARGET_PORT: MzAwMA==

# expense
expense:
  DEPLOYMENT_CONTAINER_PORT: MzAwMA==
  SERVICE_PORT: MzAwMA==
  SERVICE_TARGET_PORT: MzAwMA==

# statistics
statistics:
  DEPLOYMENT_CONTAINER_PORT: MzAwMA==
  SERVICE_PORT: MzAwMA==
  SERVICE_TARGET_PORT: MzAwMA==

# frontend
frontend:
  DEPLOYMENT_CONTAINER_PORT: ODA=
  SERVICE_PORT: ODA=
  SERVICE_TARGET_PORT: ODA=
