apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: statistics
  name: statistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistics
  template:
    metadata:
      labels:
        app: statistics
    spec:
      containers:
        - image: statistics:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: DB_HOST
              value: { { .Values.env.DB_HOST } }
            - name: DB_USER
              value: { { .Values.env.DB_USER } }
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: { { .Values.env.DB_PASSWORD } }
            - name: DB_NAME
              value: { { .Values.env.DB_NAME } }
            - name: DB_PORT
              value: { { .Values.env.DB_PORT } }
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: budgetbook
                  key: { { .Values.env.JWT_SECRET } }
          name: statistics
          ports:
            - containerPort:
                { { .Values.statistics.DEPLOYMENT_CONTAINER_PORT } }
              protocol: TCP
      restartPolicy: Always
