apiVersion: v1
kind: Service
metadata:
  name: statistics
spec:
  selector:
    app: statistics
  ports:
    - name: "http"
      port: { { .Values.statistics.SERVICE_PORT } }
      targetPort: { { .Values.statistics.SERVICE_TARGET_PORT } }
