apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - name: "http"
      port: { { .Values.auth.SERVICE_PORT } }
      targetPort: { { .Values.auth.SERVICE_TARGET_PORT } }
